//修复联系人
export const GROUPLIST = 'GROUPLIST'
export const  GROUPLIST_SUCCEEDED = 'GROUPLIST_SUCCEEDED'
export const  GROUPLIST_FAILED = 'GROUPLIST_FAILED'

//修复联系人
export const TRANSFER_COMMIT = 'TRANSFER_COMMIT'
export const  TRANSFER_COMMIT_SUCCEEDED = 'TRANSFER_COMMIT_SUCCEEDED'
export const  TRANSFER_COMMIT_FAILED = 'TRANSFER_COMMIT_FAILED'
